if(CONFIG_WBR_CONTROL_RUNTIME_INIT_LITTLEFS OR CONFIG_WBR_CONTROL_SHELL_CHASSIS_TUNING)
  file(GLOB_RECURSE WBR_CONTROL_STORAGE_SOURCES CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_SOURCE_DIR}/filesystem/littlefs_service.cpp
  )
  target_sources(wbr_platform PRIVATE ${WBR_CONTROL_STORAGE_SOURCES})
  target_link_libraries(wbr_platform PRIVATE LITTLEFS)
endif()
