CONFIG_SERIAL=y
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n
CONFIG_STDOUT_CONSOLE=n
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_HPM67_DOUBLE_PRECISION_FPU=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_ZBUS=y
CONFIG_RING_BUFFER=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_PRINTK=n
CONFIG_UART_ASYNC_API=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_CAN=y
CONFIG_SHELL=n
CONFIG_SHELL_THREAD_PRIORITY_OVERRIDE=n
# CONFIG_SHELL_THREAD_PRIORITY=7
CONFIG_TIMESLICING=y
CONFIG_TIMESLICE_SIZE=1
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_THREAD_RUNTIME_STATS_USE_TIMING_FUNCTIONS=y
CONFIG_THREAD_ANALYZER=n
CONFIG_THREAD_ANALYZER_USE_PRINTK=n
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_FILE_SYSTEM_SHELL=n
CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=n
CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_MIN=y
CONFIG_DEBUG_COREDUMP_SHELL=n

CONFIG_CHERRYUSB=y
CONFIG_CHERRYUSB_DEVICE=y
CONFIG_CHERRYUSB_DEVICE_SPEED_HS=y
CONFIG_CHERRYUSB_DEVICE_HPM=y

CONFIG_WBR_CONTROL_RUNTIME_INIT_CAN=y
CONFIG_WBR_CONTROL_RUNTIME_INIT_USB=y
CONFIG_WBR_CONTROL_PC_LINK=y
CONFIG_WBR_CONTROL_PC_LINK_PERIOD_MS=1
CONFIG_WBR_CONTROL_PC_LINK_COMMAND_TIMEOUT_MS=100
CONFIG_WBR_CONTROL_RUNTIME_INIT_LITTLEFS=n
CONFIG_WBR_CONTROL_SHELL_MAVLINK_CONTROL=n
# 默认不使用 UART0。需要输出时，通过 EXTRA_CONF_FILE 选择 config/ 下的模式配置。
CONFIG_WBR_CONTROL_UART0_OUTPUT_DISABLED=y
CONFIG_WBR_CONTROL_MODULE_REMOTE_INPUT=y
CONFIG_WBR_CONTROL_MODULE_CHASSIS=y
CONFIG_WBR_CONTROL_MODULE_REFEREE=n
CONFIG_WBR_CONTROL_MODULE_HI91_IMU=y
CONFIG_WBR_CONTROL_HI91_IMU_STRICT_CRC=y
